type(Key.CMD)
wait(5)
type("firefox" + Key.ENTER)
wait(5)
type("https://temp-mail.org/en/" + Key.ENTER)
wait(5)
click("Delete_button.png")
wait(20)
click ("copy_emal_address.png")
wait(10)
cb = Env.getClipboard()
type ("t", KEY_CTRL)
wait(10)
type("https://sandbox.xpand-it.com/secure/Dashboard.jspa" + Key.ENTER)
wait(5)

type("FN_regform_Jira.png", "Pencho")
wait(2)
type("CN_regForm_Jira.png", "Penchev LTD")
wait(2)
type("LN_regForm_Jira.png", "Penchev")
wait(2)
type("EA_regForm_Jira.png", cb)
wait(2)
click("check_box_regForm_Jira.png")
wait(2)
click("check_box_regForm_Jira.png")
wait(2)
click("Submit_Botton_regForm_Jira.png")
wait(2)
click("TM_tab.png")
type(Key.UP, KeyModifier.WIN)

click("refresh_button_TM.png")
wait(30)
click("sender_click.png")

wait("label_jira_email.png", 3600)

if exists("label_jira_email.png"):
    click("email_jira.png")

if exists("label_username.png"):
    doubleClick("label_user.png")

type ("c", KEY_CTRL)  
user = Env.getClipboard()


click("button_SetMyPass.png")
type("New_Pass_Jira_restForm.png", "Penka")
type("Confirm_resetForm_Jira.png", "Penka")
wait(2)
click("Reset_Button_resFormPass_Jira.png")
wait(2)
click("LogIn_link_Jira.png")
wait(2)

type("UserName_LogIn_Form.png", user)
wait(2)
click("WDE_text.png")
wait(2)
type("Pass_LogInForm_Jira.png", "Penka")
click("Button_logIn_Jira.png")
wait(3)
click("Project_button_jira.png")
wait(3)
click("CreateProject_button_Jira.png")
wait(3)
click("Kanban_project.png")
wait(3)
click("Button_Next.png")
wait(3)
click("Select_button_CreateProject.png")
wait(3)
import random
num = random.randrange(10000000000,10000000000000)

type("Name_CreatePojectForm_Jira.png", str(num))
wait(3)
type("Key_CreateProjectForm_Jira.png", user)
click("Submit_project.png")
wait(5)
click("Create_Issue.png")
wait(5)
if exists("bug-2.png"):
    type("1622896080922.png", "When you change the language, the currencies used in the specific countries do not change automatically")
    
if exists("story.png"):
   click ("story.png")
   
click("bug.png")


type("Summary_Bug_Report.png", "When you change the language, the currencies used in the specific countries do not change automatically")
wait(1)

type("Description.png", "*Prerquites:*" + Key.ENTER + Key.ENTER)
type("Go to url: https://phptravels.net/" + Key.ENTER + Key.ENTER)
type("*Steps to reproduce:*" + Key.ENTER + Key.ENTER)
type("1. Click on the dropdown menu *English* on the top right corner of the page;" +Key.ENTER +Key.ENTER)
type("2. Select any of the language lists;" + Key.ENTER + Key.ENTER)
type("*Expected result:*" + Key.ENTER + Key.ENTER)
type("The currency should automatically change to the one used in the country" + Key.ENTER + Key.ENTER)
type("*Actual result:*" + Key.ENTER + Key.ENTER)
type("When choosing the Russian language, the currency remains usd" + Key.ENTER + Key.ENTER)
type("*Priority:*" + Key.ENTER + Key.ENTER)
type("High" + Key.ENTER + Key.ENTER)
type("*Additional info:*" + Key.ENTER + Key.ENTER)
type("Mozilla Firefox 88.0 (64-bit), Windows 10 version 20H2" + Key.ENTER)
click("Priority.png")
click("High_.png")
click("Create_BugReport.png")
wait(1)
click("1622910819622.png")
click("SearchFieldButton.png")
wait(2)
type("1622910865745.png", "When you change the language")
click("SearchButton.png")
if exists("test_messege-1.png"):
    popup("The test performed with Sikuli was successful!")
wait(10)
if exists("pop_up-1.png"):
    type(Key.ENTER)
wait (10)
click("LogOut_Button_Jira.png")
click("logOut_Jira.png")
